apiVersion: v1
kind: Service
metadata:
  name: gin-server-loadbalancer-service
  labels:
    app: gin-server-loadbalancer-service
spec:
  type: LoadBalancer
  ports: 
    - port: 80 # port 80 is exposed at external
      targetPort: 12345
  selector: 
    app: gin-server-pod

