apiVersion: v1
kind: Service
metadata:
  name: gin-server-clusterip-service
  labels:
    app: gin-server-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: gin-server-pod
  ports:  
    - port: 80
      targetPort: 12345